### ISSUE TITLE
run in backgroud

### ISSUE THREAD

**Issue by lixlop** [andreadec/MusicPlayer#2]
Hello andreadec, Firstly, thank for share the perfect musicplayer for us.After read the code of it,I have some questions. I try to wite the code by myself . But it can not run in background on HuaWei,
also your Program  runs  perfectly on HuaWei. I want to know how do you achieve。
   I already request the Permission android.permission.WAKE_LOCK,and complete the same code as yours.
   Please help me,Thanks!

**Comment by andreadec** [comment]
If I understood well this is not a problem related with my app, so I close the issue.
Please contact me via email and I'll try to help you. Thanks.
