### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [andreadec/MusicPlayer#3]
With the last release and last commit more than 2 years ago, do you still maintain this app, @andreadec? Will there be future development/releases?

**Comment by andreadec** [comment]
Hi. Thanks for your interest in the app. I'm sorry but unfortunately I don't have time to work on it anymore. I don't have plans for future releases.

**Comment by IzzySoft** [comment]
Thanks for the answer, @andreadec – though I had hoped for a different one… So good luck with your other projects then!

**Comment by STPKITT** [comment]
I just discovered this gem of an app today. It's an audio player of the kind I was searching for years after another similar one stopped working back then. It lacks a queue & choice of color, but apart from that it's great.
Currently MusicPlayer is working absolutely fine on my devices which are not running cutting edge Android versions though so I don't know if it works on those.
I don't know how much work it is to just keep an app like this working in future Android versions but I think that's the only maintenance this app would need. I'd love to see that happening :-)
